### ISSUE TITLE
Curl based examples fail

### ISSUE THREAD

**Issue by jackzampolin** [app-registry/appr-server#36]
Very cool project!! I pulled down the repo and was able to get the server running just fine, but when I tried to run `./Documentation/test.sh` all of the curl commands besides the ones that pull down charts failed with:

```
curl -XPOST http://localhost:5000/api/v1/packages/foo/bar -d '{"blob": "H4sIAP3mAFgAA+3OMQqEMBCF4ak9RU4gGaPxPClcVogKGou9/SpYrI2yhYjwf82DeVO8LvTtq5lS/gldlGvYhfflmlpX9jc3XtStV++KSsVqobUTYy/aszNPKYzGSOiT04O/s/6h3k2MQ3b3CgAAAAAAAAAAAAAAAADAv77X4+BWACgAAA==", "release": "1.0.1", "media_type": "kpm"}'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by ant31** [comment]
Hi, 
Thanks for trying it. 

This documentation is out-dated, latest changes included a default "/cnr" prefix to all routes: 
```
curl http://localhost:5000/cnr/version
curl -XPOST http://localhost:5000/cnr/api/v1/packages/foo/bar -d '{"blob": "H4sIAP3mAFgAA+3OMQqEMBCF4ak9RU4gGaPxPClcVogKGou9/SpYrI2yhYjwf82DeVO8LvTtq5lS/gldlGvYhfflmlpX9jc3XtStV++KSsVqobUTYy/aszNPKYzGSOiT04O/s/6h3k2MQ3b3CgAAAAAAAAAAAAAAAADAv77X4+BWACgAAA==", "release": "1.0.1", "media_type": "kpm"}'
```

**Comment by jackzampolin** [comment]
Just figured this out! Thank you for this quick response @ant31! 

A quick question that might be out of band: where does the server store the data in the filesystem?

**Comment by ant31** [comment]
by default it's in `~/.cnr/packages`, 
You can also use redis or etcd as backend(instead of the FS).
 More will come and especially object-storages like GS or S3 to store blobs.

**Comment by jackzampolin** [comment]
Looking very much forward to those features!
